### ISSUE TITLE
document.documentElement  should return HtmlHtmlElement

### ISSUE THREAD

**Issue by jarrodcolburn** [dart-lang/web#214]
`document.documentElement` returns `Element?` but it should return [`HtmlHtmlElement?`](https://pub.dev/documentation/web/latest/web/HTMLHtmlElement-extension-type.html) according to [mdn's docs on HTMLHtmlElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHtmlElement)

> The HTMLHtmlElement interface serves as the root node for a given HTML document. This object inherits the properties and methods described in the [HTMLElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement) interface.

 > You can retrieve the HTMLHtmlElement object for a given document by reading the value of the [document.documentElement](https://developer.mozilla.org/en-US/docs/Web/API/Document/documentElement) property.

**Comment by ksw2000** [comment]
I think that it is due to the source we reference. 

`document.documentElement` is defined in [lib/src/dom/dom.dart](https://github.com/dart-lang/web/blob/e773de957b289d001c90c6b830e91634e305667d/lib/src/dom/dom.dart#L1814), which is referenced from [@webref/dom.idl](https://github.com/w3c/webref/blob/2027b442585f364c6089f9077248514526c11e3d/ed/idl/dom.idl#L281)

[@webref/dom.idl](https://github.com/w3c/webref/blob/2027b442585f364c6089f9077248514526c11e3d/ed/idl/dom.idl#L281)
![image](https://github.com/dart-lang/web/assets/13825170/89bc478c-820e-49ee-b8c3-5bf033fdf956)

**Comment by srujzs** [comment]
Per https://github.com/dart-lang/web/pull/217#issuecomment-2030112627, it looks like this is typed correctly as `documentElement` can return both an html element as well as other elements.
