### ISSUE TITLE
[feat] Add helper to convert HtmlCollection to a dart list

### ISSUE THREAD

**Issue by rutvik110** [dart-lang/web#281]
### **Issue:** 

When working with html element childrens which are represented through the `HtmlCollection`, if someone wants to iterate through these childrens in dart, only approach is to use a  `for` loop like follow to either create a dart list which would then allow running operations like `forEach`, `map`, etc on the list or simply iterate through them to execute any functions. 

```dart
      final childrens = <Element>[];

      for (var i = 0; i < element.children.length; i++) {
        final child = element.children.item(i);

        childrens.add(child);
      }
```

This works but it becomes tedious when I've to do the same thing in multiple places. Off course, I could add an extension for this on `HtmlCollection` but it would be nice if such helper was present in `web` package itself. 

`TouchListConvert` extension on `TouchList` is an example of such helper. And the approach seems better instead of running a for loop which results in extra computations. Adding a similar helper for converting `HtmlCollection` to a dart list would be nice addition I believe. 

### **Proposal:** 

I can see this addition going two ways, 

1. Add a similar extension on `HtmlCollection` like `TouchListConvert` that would return a `HtmlCollectionWrapper` that would be a dart list.
2. Create a generic wrapper like `TouchListConvert` which could work for both `TouchListConvert` and `HtmlCollection`, and also other web facing apis like `NodeList` that represent a list of items. This one I'm not so sure abt how one would approach for this scenario.

**Comment by ykmnkmi** [comment]
You can use `Array.from` (related dart-lang/sdk#56069):

```dart
import 'dart:js_interop';

import 'package:web/web.dart';

@JS('Array.from')
external JSArray<T> arrayFrom<T extends JSAny?>(JSAny any);

void main() {
  var body = document.body as HTMLElement;
  var children = arrayFrom<Node>(body.children);

  for (var child in children.toDart) {
    print(child.textContent);
  }
}
```

**Comment by rutvik110** [comment]
What would you say is more efficient in terms of computations between 1. the approach you suggested 2. Using for loop it create list on dart side 3. The approach used by `TouchListConvert`.?

Given I've to do this hundreds of times over wide array of childrens in my web project at any given moment, I believe the third approach could be the most efficient as there's no overhead of computations from creating a list or rather conversation from dart-js interop. Probably the reason why that approach was used within `TouchListConvert` or may be some other reason.

**Comment by srujzs** [comment]
Similar issue: https://github.com/dart-lang/web/issues/101

> And the approach seems better instead of running a for loop which results in extra computations.

The end result will be the same here in terms of performance. We'll still need to iterate.

I think option 2 is the best bet here. We can make this a generic List wrapper (with `T` being `Touch` for `TouchListWrapper`) around a `JSObject` so that that wrapper can be used for other types besides just `HtmlCollection` (maybe some of the `iterable` types if users want).

> What would you say is more efficient in terms of computations between 1. the approach you suggested 2. Using for loop it create list on dart side 3. The approach used by TouchListConvert.?

I answered this partially on the `Array.from` request, but it depends on if you have a lot of accesses or a lot of creations. That being said, 3 avoids the `Array.from` call, so it should likely be faster than 1, but maybe array accesses are faster than accesses on `TouchList` for example. Either way, users should have all these options so they can decide based on their use-case.

**Comment by rutvik110** [comment]
> Either way, users should have all these options so they can decide based on their use-case.

@srujzs  Correct me if I'm wrong, so we're planning to add all these 3 options to give users options to pick the best one for them,

1. `arrayFrom` external method. This is already proposed for dart sdk but I'm not sure on the timeline of when it'll be added. But it should be a simple addition to  existing `JSArray` I believe. I can put a PR on this for dart sdk if there isn't one already.
2. A generic list wrapper around `JSObject ` that uses for-loop to create dart list. Part of `web` package.

About the 3rd option, creating generic implementation of `TouchListWrapper`, how do you propose we do this?

**Comment by srujzs** [comment]
1. Yup, it should be a simple addition as a static method. Feel free to contribute, happy to take PRs!
2. I meant this as users can do this themselves already with a simple for-loop (it's essentially what you wrote in the first comment). We could add a helper here, but it likely doesn't buy much over option (3).
3. Most of these list-like types have similar interfaces in the JS side e.g. [DOMRectList](https://github.com/w3c/webref/blob/2bc66526d5c440586a4ffad7e026a18f02be3367/tr/idl/geometry.idl#L84). There's an accessor and a length property, and that's it. The current `TouchListWrapper` implementation can be made generic by instead taking a `T extends JSObject`, and replacing `Touch`s with `T`. The list-like `JSObject` (in this case, `TouchList`) will have to be assumed to have `length` and `item` properties since we don't have a shared interface type for all these APIs, but besides that quirk, it should work out neatly. We don't need more features than what `TouchListWrapper` provides as that should be sufficient to be at parity with `dart:html`. I could take this on.

**Comment by rutvik110** [comment]
That clarifies the doubts I had. 
No problem. I can push on both `1` and `3`. Thanx for the clarifications!
