### ISSUE TITLE
Preferred way to convert a `JSAny`

### ISSUE THREAD

**Issue by arnaud-secondlayer** [dart-lang/web#310]
`HTMLDivElement` function `innerHTML` returns `JSAny`.
I'd like to convert it to a darlang `String`.

What is the preferred solution? I can think of two, but there could be others as well.

```
final str =  (div.innerHTML as JSString).toDart;
```

```
final str =  div.innerHTML.toString();
```

My criterion for preferred solution would probably be that the generated javascript is the simplest possible.

**Comment by srujzs** [comment]
They should both work, but the first one is preferred so that you're not relying on the behavior of `toString`. As for code size/performance, they should be similar e.g.

```JavaScript
// dart2js
A._asString(t1._as(_this.innerHTML)) // first
J.toString$0$(t1._as(_this.innerHTML)) // second
```

Both do a `typeof` check but the second one goes through roughly an extra call to intercept the type. In dart2wasm, they should also be similar in performance/code-size (one interop call to convert a JS string to a Dart `String`)

For context on why this needed to be a `JSAny`: this API can possibly [return](https://github.com/w3c/webref/blob/f2741e4c1aff2765a0313092457af610d2cd0ce7/ed/idl/html.idl#L2298) a `TrustedHTML` instead of a string.

**Comment by arnaud-secondlayer** [comment]
Thanks
