### ISSUE TITLE
Constructors for some DOM types may simply throw.

### ISSUE THREAD

**Issue by joshualitt** [dart-lang/web#53]
Currently, there are many constructors that throw. For example, `web.HTMLDivElement()`. We should either lower these like `dart:html` to `document.createElement`, or we should find some way to disallow invoking the constructor statically, i.e. a lint.

**Comment by eernstg** [comment]
Would `abstract class` work?

**Comment by joshualitt** [comment]
Hmm, maybe it would? Would you prefer a magic constructor that calls `document.createElement` or should we make it a static error to use the constructor?

**Comment by eernstg** [comment]
I was just suggesting `abstract` because that seemed to be a good fit for one of the approaches that you mentioned: 'disallow invoking the constructor statically'. That would prevent instance creations and still allow superinitializations in other constructors (but it looks like there are no subclass relationships, only `implements`, so we can't have `super(...)` anyway). On the other hand, if `document.createElement("Something")` can actually be called with an argument that yields a useful outcome then that sounds more pragmatic.

In any case, I just noticed the language perspective on this question&mdash;it would a serious mistake to assume that I can say anything useful about web programming. ;-)

**Comment by eernstg** [comment]
> we can simply omit a constructor altogether?

I would think so.

**Comment by sigmundch** [comment]
I ran again into these, so I'd suggest we do make a change to make these stand out more easily:
* add a `_` constructor that throws. This changes the default behavior and removes the default constructor from our classes:
```dart
@staticInterop @JS
class HTMLDivElement ... {
  HTMLDivElement._() => throw "unsupported";
}
```
* once we have the new language syntax, we can leave them out entirely.
* once the language introduces static extension members, we can introduce factories that call `document.createElement` from the glue layer.

**Comment by srujzs** [comment]
Handled in https://github.com/dart-lang/web/pull/185.
