### ISSUE TITLE
Consider using `num` instead of `double` for parameter types

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/web#57]
This is more backwards compatible with types used in dart:html, and hence less work to adapt a call that used to pass num or int arguments.

**Comment by srujzs** [comment]
Reopening due to concerns around users accidentally downcasting `num` in dart2wasm because they may assume dart2wasm has the same number semantics as the JS compilers (it does not).

A compromise here to:

- Make migration and passing in integer values easier
- Avoid the accidental downcasting

is to keep the parameter types as `num` but the return types as `double`.

cc @eyebrowsoffire

**Comment by parlough** [comment]
I also think this would be worth reevaluating. My feeling is that today's Dart developers aren't as familiar with `num` as they used to be.

Cases passing int literals would keep working with `double` and since there are changes you need to make when switching to `package:web` anyway, I think handling the occasional number change shouldn't be too bad. It might even be a helpful thing for that decision to be made more consciously.

**Comment by srujzs** [comment]
I agree. I want to perhaps include this in the next major release (which we'll certainly have as we tackle other issues). It does mean a little bit of pain for migration, but it should be minimal.

> My feeling is that today's Dart developers aren't as familiar with num as they used to be.

Most developers aren't aware of the number differences partly because it derives from a web vs native difference. Now that we have the number difference within web, this will pop up more often.
