### ISSUE TITLE
Expose types of `TypedData` or `JSTypedArray`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/web#65]
```
typedef ArrayBufferView = JSAny?;
typedef BufferSource = JSAny?;
typedef AllowSharedBufferSource = JSAny?;
```

This may be a more specific version of an issue related to

https://github.com/dart-lang/web/blob/0344abd564f2094fb476f3d88cfbf1a581eb6e03/tool/bindings_generator/translator.dart#L110-L113

**Comment by kevmoo** [comment]
See https://webidl.spec.whatwg.org/#ArrayBufferView and https://webidl.spec.whatwg.org/#BufferSource

**Comment by srujzs** [comment]
Note that the first two typedefs will resolve to `JSObject` since they are a union of `DataView`, which doesn't implement `TypedArray`. The last one is a union of `SharedArrrayBuffer` which doesn't have a supertype, although maybe we can include it as an alias in our type_aliases? We default to `JSAny?` in a lot of cases but maybe we can and should do better and default to `JSObject` instead.

**Comment by srujzs** [comment]
Union types have been added.
